$(function(){
    $('#programas').hide();
    $('#noticias').hide();
    $('#foro').hide();
    $('#menu').hide();
    $('#escomercado').hide();
    $('#sesion').hide();
    $('#inicio').show();
    $('#navPrincipal').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').show();
    });
    $('#navProgramas').click(function(){
        $('#programas').show();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navNoticias').click(function(){
        $('#programas').hide();
        $('#noticias').show();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navForo').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').show();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navMenu').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').show();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navEscomercado').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').show();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navSesion').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').show();
        $('#inicio').hide();
    });
    $('#navProgramas1').click(function(){
        $('#programas').show();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navNoticias1').click(function(){
        $('#programas').hide();
        $('#noticias').show();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navForo1').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').show();
        $('#menu').hide();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navMenu1').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').show();
        $('#escomercado').hide();
        $('#sesion').hide();
        $('#inicio').hide();
    });
    $('#navEscomercado1').click(function(){
        $('#programas').hide();
        $('#noticias').hide();
        $('#foro').hide();
        $('#menu').hide();
        $('#escomercado').show();
        $('#sesion').hide();
        $('#inicio').hide();
    });
});